services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: verus
      POSTGRES_PASSWORD: "13p6dVMHPWAwCWNZd7_KF2BhoYfgoAti"
    volumes:
      - verus_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "6O6D6ZrcaISaFvczP7ShZ2ecFOybxHGb"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: verus_test
      POSTGRES_PASSWORD: "Zfp-uIn_gp3HRb0WjJfO_yjHwbo4z5GQ"
    volumes:
      - verus_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "Jb84HjogtQ8YzGsZFfdSS2AwpDpmV5Hy"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  verus_data:
  verus_test_data:
